version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tg_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  server:
    build: ./server
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tg_game?schema=public
      - BOT_TOKEN=${BOT_TOKEN}
      - CORS_ORIGIN=*
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  bot:
    build: ./bot
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL:-http://localhost:5173}
    depends_on:
      - server

  webapp:
    build: ./webapp
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  db_data:
